resources:
  - url: http://127.0.0.1:5000/Home-Assistant-Mail-And-Packages-Custom-Card.js
    type: module
views:
  - cards:
      - type: custom:mailandpackagescard
        name: Mail and Packages Card Development
